// districtData.js
const districtData = [
  { name: 'Achham', blogUrl: '/achham-blog' },
  { name: 'Arghakhanchi', blogUrl: '/arghakhanchi-blog' },
  { name: 'Baglung', blogUrl: '/baglung-blog' },
  { name: 'Baitadi', blogUrl: '/baitadi-blog' },
  { name: 'Bajhang', blogUrl: '/bajhang-blog' },
  { name: 'Bajura', blogUrl: '/bajura-blog' },
  { name: 'Banke', blogUrl: '/banke-blog' },
  { name: 'Bara', blogUrl: '/bara-blog' },
  { name: 'Bardiya', blogUrl: '/bardiya-blog' },
  { name: 'Bhaktapur', blogUrl: '/bhaktapur-blog' },
  { name: 'Bhojpur', blogUrl: '/bhojpur-blog' },
  { name: 'Chitwan', blogUrl: '/chitwan-blog' },
  { name: 'Dadeldhura', blogUrl: '/dadeldhura-blog' },
  { name: 'Dailekh', blogUrl: '/dailekh-blog' },
  { name: 'Dang', blogUrl: '/dang-blog' },
  { name: 'Darchula', blogUrl: '/darchula-blog' },
  { name: 'Dhading', blogUrl: '/dhading-blog' },
  { name: 'Dhankuta', blogUrl: '/dhankuta-blog' },
  { name: 'Dharan', blogUrl: '/dharan-blog' },
  { name: 'Dhanusa', blogUrl: '/dhanusa-blog' },
  { name: 'Dolakha', blogUrl: '/dolakha-blog' },
  { name: 'Dolpa', blogUrl: '/dolpa-blog' },
  { name: 'Doti', blogUrl: '/doti-blog' },
  { name: 'Gorkha', blogUrl: '/gorkha-blog' },
  { name: 'Gulmi', blogUrl: '/gulmi-blog' },
  { name: 'Humla', blogUrl: '/humla-blog' },
  { name: 'Ilam', blogUrl: '/ilam-blog' },
  { name: 'Jajarkot', blogUrl: '/jajarkot-blog' },
  { name: 'Jhapa', blogUrl: '/jhapa-blog' },
  { name: 'Jumla', blogUrl: '/jumla-blog' },
  { name: 'Kailali', blogUrl: '/kailali-blog' },
  { name: 'Kalikot', blogUrl: '/kalikot-blog' },
  { name: 'Kanchanpur', blogUrl: '/kanchanpur-blog' },
  { name: 'Kapilvastu', blogUrl: '/kapilvastu-blog' },
  { name: 'Kaski', blogUrl: '/kaski-blog' },
  { name: 'Kathmandu', blogUrl: '/kathmandu-blog' },
  { name: 'Kavrepalanchok', blogUrl: '/kavrepalanchok-blog' },
  { name: 'Khotang', blogUrl: '/khotang-blog' },
  { name: 'Lalitpur', blogUrl: '/lalitpur-blog' },
  { name: 'Lamjung', blogUrl: '/lamjung-blog' },
  { name: 'Mahottari', blogUrl: '/mahottari-blog' },
  { name: 'Makwanpur', blogUrl: '/makwanpur-blog' },
  { name: 'Manang', blogUrl: '/manang-blog' },
  { name: 'Morang', blogUrl: '/morang-blog' },
  { name: 'Mugu', blogUrl: '/mugu-blog' },
  { name: 'Mustang', blogUrl: '/mustang-blog' },
  { name: 'Myagdi', blogUrl: '/myagdi-blog' },
  { name: 'Nawalparasi', blogUrl: '/nawalparasi-blog' },
  { name: 'Nuwakot', blogUrl: '/nuwakot-blog' },
  { name: 'Okhaldhunga', blogUrl: '/okhaldhunga-blog' },
  { name: 'Palpa', blogUrl: '/palpa-blog' },
  { name: 'Panchthar', blogUrl: '/panchthar-blog' },
  { name: 'Parbat', blogUrl: '/parbat-blog' },
  { name: 'Parsa', blogUrl: '/parsa-blog' },
  { name: 'Pyuthan', blogUrl: '/pyuthan-blog' },
  { name: 'Ramechhap', blogUrl: '/ramechhap-blog' },
  { name: 'Rasuwa', blogUrl: '/rasuwa-blog' },
  { name: 'Rautahat', blogUrl: '/rautahat-blog' },
  { name: 'Rolpa', blogUrl: '/rolpa-blog' },
  { name: 'Rukum', blogUrl: '/rukum-blog' },
  { name: 'Rupandehi', blogUrl: '/rupandehi-blog' },
  { name: 'Salyan', blogUrl: '/salyan-blog' },
  { name: 'Sankhuwasabha', blogUrl: '/sankhuwasabha-blog' },
  { name: 'Saptari', blogUrl: '/saptari-blog' },
  { name: 'Sarlahi', blogUrl: '/sarlahi-blog' },
  { name: 'Sindhuli', blogUrl: '/sindhuli-blog' },
  { name: 'Sindhupalchok', blogUrl: '/sindhupalchok-blog' },
  { name: 'Siraha', blogUrl: '/siraha-blog' },
  { name: 'Solukhumbu', blogUrl: '/solukhumbu-blog' },
  { name: 'Sunsari', blogUrl: '/sunsari-blog' },
  { name: 'Surkhet', blogUrl: '/surkhet-blog' },
  { name: 'Syangja', blogUrl: '/syangja-blog' },
  { name: 'Tanahu', blogUrl: '/tanahu-blog' },
  { name: 'Taplejung', blogUrl: '/taplejung-blog' },
  { name: 'Terhathum', blogUrl: '/terhathum-blog' },
  { name: 'Udayapur', blogUrl: '/udayapur-blog' },
  { name: 'Everest Base Camp', blogUrl: '/everest-base-camp-blog' },
  { name: 'Annapurna Base Camp', blogUrl: '/annapurna-base-camp-blog' },
  // Add more districts and destinations as needed
];

export default districtData;
